using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace WinCare.SourceGenerators
{
    [Generator]
    public sealed class CommandDispatcherGenerator : IIncrementalGenerator
    {
        private static readonly DiagnosticDescriptor DuplicateCommandId = new(
            id: "WINCARE001",
            title: "Duplicate command handler ID",
            messageFormat: "Command ID '{0}' is assigned to both '{1}' and '{2}'",
            category: "WinCare.Commands",
            defaultSeverity: DiagnosticSeverity.Error,
            isEnabledByDefault: true);

        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            var classDeclarations = context.SyntaxProvider
                .CreateSyntaxProvider(
                    predicate: static (s, _) => s is ClassDeclarationSyntax c && c.AttributeLists.Count > 0,
                    transform: static (ctx, _) => GetSemanticTargetForGeneration(ctx))
                .Where(static m => m is not null);

            var compilationAndClasses = context.CompilationProvider.Combine(classDeclarations.Collect());

            context.RegisterSourceOutput(compilationAndClasses,
                static (spc, source) => Execute(source.Left, source.Right!, spc));
        }

        private static ClassDeclarationSyntax? GetSemanticTargetForGeneration(GeneratorSyntaxContext context)
        {
            var classDecl = (ClassDeclarationSyntax)context.Node;
            foreach (var attributeList in classDecl.AttributeLists)
            {
                foreach (var attribute in attributeList.Attributes)
                {
                    if (context.SemanticModel.GetSymbolInfo(attribute).Symbol is IMethodSymbol attributeSymbol)
                    {
                        var attributeContainingTypeSymbol = attributeSymbol.ContainingType;
                        var fullName = attributeContainingTypeSymbol.ToDisplayString();

                        if (fullName == "WinCare.Domain.Attributes.CommandHandlerAttribute")
                        {
                            return classDecl;
                        }
                    }
                }
            }
            return null;
        }

        private static void Execute(Compilation compilation, IEnumerable<ClassDeclarationSyntax> classes, SourceProductionContext context)
        {
            var builder = new StringBuilder();
            builder.AppendLine("// <auto-generated/>");
            builder.AppendLine("#nullable enable");
            builder.AppendLine("using System;");
            builder.AppendLine("using System.Threading;");
            builder.AppendLine("using System.Threading.Tasks;");
            builder.AppendLine("using WinCare.Domain.Commands;");
            builder.AppendLine();
            builder.AppendLine("namespace WinCare.Application.Commands");
            builder.AppendLine("{");
            builder.AppendLine("    public static partial class GeneratedCommandDispatcher");
            builder.AppendLine("    {");
            builder.AppendLine("        public static bool TryRouteStatic(string commandId, out string handlerTypeName)");
            builder.AppendLine("        {");
            builder.AppendLine("            switch (commandId?.ToLowerInvariant())");
            builder.AppendLine("            {");

            var routes = new SortedDictionary<string, (string Handler, Location? Location)>(System.StringComparer.OrdinalIgnoreCase);
            var ambiguousIds = new HashSet<string>(System.StringComparer.OrdinalIgnoreCase);
            foreach (var classDecl in classes.Distinct())
            {
                var model = compilation.GetSemanticModel(classDecl.SyntaxTree);
                if (model.GetDeclaredSymbol(classDecl) is INamedTypeSymbol classSymbol)
                {
                    foreach (var attr in classSymbol.GetAttributes())
                    {
                        if (attr.AttributeClass?.ToDisplayString() == "WinCare.Domain.Attributes.CommandHandlerAttribute" &&
                            attr.ConstructorArguments.Length > 0)
                        {
                            var cmdId = attr.ConstructorArguments[0].Value?.ToString();
                            if (string.IsNullOrEmpty(cmdId))
                            {
                                continue;
                            }

                            string handler = classSymbol.ToDisplayString();
                            Location? location = classDecl.Identifier.GetLocation();
                            if (routes.TryGetValue(cmdId!, out var existing))
                            {
                                if (!string.Equals(existing.Handler, handler, System.StringComparison.Ordinal))
                                {
                                    ambiguousIds.Add(cmdId!);
                                    context.ReportDiagnostic(Diagnostic.Create(
                                        DuplicateCommandId,
                                        location,
                                        cmdId,
                                        existing.Handler,
                                        handler));
                                }
                            }
                            else
                            {
                                routes.Add(cmdId!, (handler, location));
                            }
                        }
                    }
                }
            }

            foreach (var route in routes)
            {
                if (ambiguousIds.Contains(route.Key))
                {
                    continue;
                }

                builder.AppendLine($"                case {Microsoft.CodeAnalysis.CSharp.SymbolDisplay.FormatLiteral(route.Key.ToLowerInvariant(), quote: true)}:");
                builder.AppendLine($"                    handlerTypeName = {Microsoft.CodeAnalysis.CSharp.SymbolDisplay.FormatLiteral(route.Value.Handler, quote: true)};");
                builder.AppendLine("                    return true;");
            }

            builder.AppendLine("                default:");
            builder.AppendLine("                    handlerTypeName = string.Empty;");
            builder.AppendLine("                    return false;");
            builder.AppendLine("            }");
            builder.AppendLine("        }");
            builder.AppendLine("    }");
            builder.AppendLine("}");

            context.AddSource("GeneratedCommandDispatcher.g.cs", SourceText.From(builder.ToString(), Encoding.UTF8));
        }
    }
}
