function Install-WinCarePackage {
    [CmdletBinding(SupportsShouldProcess,ConfirmImpact='Medium')]
    param([Parameter(Mandatory)][string]$SourceRoot,[Parameter(Mandatory)][string]$Destination,[switch]$NoStartMenuShortcut,[switch]$Force,[switch]$Repair,[string]$ShortcutRoot)
    if($Force -and $Repair){throw 'Choose either -Force or -Repair.'};$source=Get-WinCareReleaseIdentity ([IO.Path]::GetFullPath($SourceRoot));$dest=Assert-WinCareManagedPath $Destination;$parent=Get-WinCareParentPath $dest
    $id=[guid]::NewGuid();$operation='install';$old=$null;$exists=Test-Path -LiteralPath $dest
    if($exists){if(!$Force -and !$Repair){throw 'Destination exists. Use -Force to recover or replace a WinCare installation, or -Repair for a managed installation.'};try{$old=Read-WinCareInstallMarker $dest}catch{if($Repair){throw 'Repair requires a valid managed WinCare installation marker.'};if(!(Test-WinCareRecoverableDestination $dest)){throw 'Refusing to overwrite an unmanaged destination, even with -Force.'}};if($old){$id=[guid]$old.InstallationId;$operation=if($Repair){'repair'}else{'replace'};if(!$Repair){try{Test-WinCareManagedReleaseTree $dest -AllowInstallMarker|Out-Null}catch{$operation='recover'}}}else{$operation='recover'}}
    if(!$PSCmdlet.ShouldProcess($dest,"$operation WinCare")){return};[void][IO.Directory]::CreateDirectory($parent);$stage=Join-Path $parent ('.WinCare.stage-'+[guid]::NewGuid().ToString('N'));$backup=Join-Path $parent ('.WinCare.backup-'+[guid]::NewGuid().ToString('N'));$moved=$false;$committed=$false;$shortcutTx=$null;$createdShortcutFolder=$null
    try{Copy-Item -LiteralPath $source.Tree.Root -Destination $stage -Recurse -Force -ErrorAction Stop;$stageTree=Test-WinCareManagedReleaseTree $stage;$marker=[ordered]@{SchemaVersion=$script:MarkerSchema;Product='WinCare';ProductGuid=$script:ProductGuid;ManifestGuid=$script:ProductGuid;InstallationId=$id.ToString();Version=[string]$source.Module.ModuleVersion;DestinationPathSha256=Get-WinCareCanonicalPathHash $dest;ReleaseManifestSha256=$stageTree.ManifestSha256;ManifestFileCount=$stageTree.Files;BuildReceiptSha256=$source.ReceiptSha256;InstalledAt=[datetime]::UtcNow.ToString('o');LastOperation=$operation;ShortcutFolder=$null};Write-WinCareJson (Join-Path $stage '.wincare-install.json') $marker;if($exists){Move-Item -LiteralPath $dest -Destination $backup -ErrorAction Stop;$moved=$true};Move-Item -LiteralPath $stage -Destination $dest -ErrorAction Stop;$committed=$true
        $manageShortcuts=!$NoStartMenuShortcut -or ($old -and $old.ShortcutFolder);if($manageShortcuts){$shortcutTx=Move-WinCareShortcutFolderToBackup $ShortcutRoot};if(!$NoStartMenuShortcut){$createdShortcutFolder=Install-WinCareShortcuts $dest $id $ShortcutRoot;$marker.ShortcutFolder=$createdShortcutFolder};Write-WinCareJson (Join-Path $dest '.wincare-install.json') $marker;Test-WinCareManagedReleaseTree $dest -AllowInstallMarker|Out-Null;$installed=Read-WinCareInstallMarker $dest;if($installed.ReleaseManifestSha256 -ne $stageTree.ManifestSha256 -or $installed.BuildReceiptSha256 -ne $source.ReceiptSha256){throw 'Installed marker does not match verified release evidence.'};if($moved -and (Test-Path -LiteralPath $backup)){Remove-WinCareTree $backup};if($shortcutTx -and $shortcutTx.Backup -and (Test-Path -LiteralPath $shortcutTx.Backup)){try{Remove-WinCareTree $shortcutTx.Backup}catch{Write-Warning "Installed successfully, but the previous shortcut backup could not be removed: $($_.Exception.Message)"}};[pscustomobject]@{Status='installed';Operation=$operation;Destination=$dest;InstallationId=$id}
    }catch{if($createdShortcutFolder -and (Test-Path -LiteralPath $createdShortcutFolder)){try{Remove-WinCareTree $createdShortcutFolder}catch{Write-Warning "Created shortcut rollback failed: $($_.Exception.Message)"}};if($shortcutTx){try{Restore-WinCareShortcutBackup $shortcutTx}catch{Write-Warning "Shortcut rollback failed: $($_.Exception.Message)"}};if($committed -and (Test-Path -LiteralPath $dest)){try{Remove-WinCareTree $dest}catch{}};if($moved -and (Test-Path -LiteralPath $backup) -and !(Test-Path -LiteralPath $dest)){Move-Item -LiteralPath $backup -Destination $dest -ErrorAction Stop};throw}finally{if(Test-Path -LiteralPath $stage){try{Remove-WinCareTree $stage}catch{}}}
}
function Uninstall-WinCarePackage {
    [CmdletBinding(SupportsShouldProcess,ConfirmImpact='High')]
    param([Parameter(Mandatory)][string]$Destination,[switch]$PurgeData,[switch]$RemoveCorruptInstallation,[string]$ShortcutRoot)
    $dest=Assert-WinCareManagedPath $Destination;if(!(Test-Path -LiteralPath $dest)){return [pscustomobject]@{Status='not-installed'}};$marker=$null
    try{$marker=Read-WinCareInstallMarker $dest}catch{if(!$RemoveCorruptInstallation){throw};if(!(Test-WinCareRecoverableDestination $dest)){throw 'Refusing to remove an unmanaged destination, even with -RemoveCorruptInstallation.'}};if(!$RemoveCorruptInstallation){Test-WinCareManagedReleaseTree $dest -AllowInstallMarker|Out-Null};if(!$PSCmdlet.ShouldProcess($dest,'uninstall WinCare')){return}
    $tomb=Join-Path (Get-WinCareParentPath $dest) ('.WinCare.remove-'+[guid]::NewGuid().ToString('N'));Move-Item -LiteralPath $dest -Destination $tomb -ErrorAction Stop;$shortcutTx=$null;$treeRemoved=$false
    try{if($marker){$check=Read-WinCareInstallMarker $tomb -SkipPathBinding;if($check.InstallationId -ne $marker.InstallationId){throw 'Tombstone identity changed.'}};if(!$RemoveCorruptInstallation){Test-WinCareManagedReleaseTree $tomb -AllowInstallMarker|Out-Null};$shortcutTx=if($marker){Move-WinCareOwnedShortcutsToBackup $marker $dest $ShortcutRoot}elseif($RemoveCorruptInstallation){try{Move-WinCareExpectedOwnedShortcutsToBackup $dest $ShortcutRoot}catch{Write-Warning "WinCare installation was corrupt; owned shortcut cleanup was preserved for safety: $($_.Exception.Message)";$null}};Remove-WinCareTree $tomb;$treeRemoved=$true}catch{if($shortcutTx){try{Restore-WinCareShortcutBackup $shortcutTx}catch{Write-Warning "Shortcut rollback failed: $($_.Exception.Message)"}};if((Test-Path -LiteralPath $tomb) -and !(Test-Path -LiteralPath $dest)){Move-Item -LiteralPath $tomb -Destination $dest -ErrorAction SilentlyContinue};throw}
    if($treeRemoved -and $shortcutTx -and $shortcutTx.Backup -and (Test-Path -LiteralPath $shortcutTx.Backup)){try{Remove-WinCareTree $shortcutTx.Backup}catch{Write-Warning "WinCare was uninstalled, but the shortcut tombstone could not be removed: $($_.Exception.Message)"}}
    $purged=$false;if($PurgeData){$data=Join-Path $env:LOCALAPPDATA 'WinCare';if(Test-Path -LiteralPath $data){try{$identityPath=Join-Path $data '.wincare-data.json';if(!(Test-Path -LiteralPath $identityPath -PathType Leaf)){throw 'data identity marker is missing'};$identity=Read-WinCareJson $identityPath 65536;if($identity.Product -ne 'WinCare' -or $identity.ManifestGuid -ne $script:ProductGuid -or $identity.RootSha256 -ne (Get-WinCareCanonicalPathHash $data)){throw 'data identity marker is invalid'};Remove-WinCareTree $data;$purged=$true}catch{Write-Warning "WinCare was uninstalled, but unrecognized data was preserved: $($_.Exception.Message)"}}}
    [pscustomobject]@{Status='uninstalled';Destination=$dest;RemovedCorruptInstallation=[bool]$RemoveCorruptInstallation;PurgedData=$purged}
}
