Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

$script:WinCareModuleRoot = $PSScriptRoot
$moduleVersion = $ExecutionContext.SessionState.Module.Version
if ($null -eq $moduleVersion) {
    throw 'WinCare must be imported through WinCare.psd1 so the module version is authoritative.'
}
$script:WinCareVersion = $moduleVersion.ToString()
$script:WinCareSourceManifestFiles = @(
    'SourceManifests/Core.psd1'
    'SourceManifests/Providers.psd1'
    'SourceManifests/UI.psd1'
)
$script:WinCareSourceGroups = @(
    [pscustomobject]@{ Name='Core'; Manifest='SourceManifests/Core.psd1'; Folders=@('Core') }
    [pscustomobject]@{ Name='Providers'; Manifest='SourceManifests/Providers.psd1'; Folders=@('Providers') }
    [pscustomobject]@{ Name='UI'; Manifest='SourceManifests/UI.psd1'; Folders=@('UI','UI/Gui','UI/Screens') }
)
$expectedModuleFiles = [Collections.Generic.List[string]]::new()
foreach ($group in $script:WinCareSourceGroups) {
    if ([string]$group.Manifest -notin $script:WinCareSourceManifestFiles) {
        throw "Source group $($group.Name) is not declared in WinCareSourceManifestFiles."
    }
    $manifestPath = Join-Path $PSScriptRoot ([string]$group.Manifest)
    if (-not (Test-Path -LiteralPath $manifestPath -PathType Leaf)) {
        throw "Required source manifest is missing: $($group.Manifest)"
    }
    $sourceManifest = Import-PowerShellDataFile -LiteralPath $manifestPath
    if ([int]($sourceManifest.SchemaVersion) -ne 1 -or [string]($sourceManifest.Group) -ne [string]($group.Name)) {
        throw "Source manifest identity is invalid: $($group.Manifest)"
    }
    $declared = @($sourceManifest.Files | ForEach-Object { ([string]$_).Replace('\','/') })
    $duplicates = @($declared | Group-Object | Where-Object Count -gt 1 | ForEach-Object Name)
    if ($duplicates.Count) { throw "Duplicate source entries in $($group.Manifest): $($duplicates -join ', ')" }
    $actual = [Collections.Generic.List[string]]::new()
    foreach ($folder in @($group.Folders)) {
        $folderPath = Join-Path $PSScriptRoot ([string]$folder)
        if (-not (Test-Path -LiteralPath $folderPath -PathType Container)) { throw "Required module source directory is missing: $folder" }
        foreach ($file in Get-ChildItem -LiteralPath $folderPath -Filter '*.ps1' -File | Sort-Object Name) {
            $actual.Add([IO.Path]::GetRelativePath($PSScriptRoot, $file.FullName).Replace('\','/'))
        }
    }
    $missing = @($declared | Where-Object { $_ -notin $actual })
    $unexpected = @($actual | Where-Object { $_ -notin $declared })
    if ($missing.Count -or $unexpected.Count) {
        $parts = [Collections.Generic.List[string]]::new()
        if ($missing.Count) { $parts.Add('missing=' + ($missing -join ',')) }
        if ($unexpected.Count) { $parts.Add('unexpected=' + ($unexpected -join ',')) }
        throw "WinCare $($group.Name) source manifest mismatch: $($parts -join '; ')"
    }
    if (($declared -join "`n") -ne (@($actual) -join "`n")) {
        throw "WinCare $($group.Name) source manifest order is not canonical."
    }
    foreach ($relativePath in $declared) { $expectedModuleFiles.Add($relativePath) }
}
$duplicateModuleFiles = @($expectedModuleFiles | Group-Object | Where-Object Count -gt 1 | ForEach-Object Name)
if ($duplicateModuleFiles.Count) { throw ('Source files assigned to multiple groups: ' + ($duplicateModuleFiles -join ', ')) }
foreach ($relativePath in $expectedModuleFiles) {
    $sourcePath = Join-Path $PSScriptRoot $relativePath
    . $sourcePath
}
Export-ModuleMember -Function @(
    'Start-WinCare',
    'Start-WinCareMetricsHttpServer',
    'Get-WinCareMetricsHttpServerState',
    'Stop-WinCareMetricsHttpServer',
    'Initialize-WinCareState',
    'Invoke-WinCareHeadlessCommand',
    'Get-WinCareHeadlessCommandName',
    'Get-WinCareSystemSummary',
    'Get-WinCareInstalledApplication',
    'Get-WinCareCleanupTarget',
    'Get-WinCareDriveSummary',
    'Get-WinCareStartupItem',
    'Get-WinCareHealthFinding',
    'Get-WinCareSecuritySummary',
    'Get-WinCareNetworkSummary',
    'Get-WinCareCatalog',
    'Get-WinCarePreset',
    'New-WinCarePresetPlan',
    'New-WinCareCatalogPlan',
    'Get-WinCareWuaUpdate',
    'Get-WinCareWuaHistory',
    'Get-WinCareWdacActivePolicy',
    'Get-WinCareCodeIntegrityEvent',
    'Get-WinCareProcessInternals',
    'Get-WinCareMemoryInternals',
    'Get-WinCareProcessorTopology',
    'Get-WinCareCredentialProvider',
    'Get-WinCareDesktopControlSummary',
    'Get-WinCareWifiProfile',
    'Get-WinCareShellExtension',
    'Get-WinCareBootDiagnostics',
    'Get-WinCareUnattendAnalysis',
    'Import-WinCareProvisioningBlueprint',
    'New-WinCareProvisioningPlan',
    'Export-WinCareProvisioningKit',
    'Get-WinCareKnowledgeBase',
    'New-WinCareSystemReportData',
    'Get-WinCareAutomationProfile',
    'Invoke-WinCareAutomationProfile',
    'Get-WinCareUndoableOperation',
    'New-WinCareUndoPlan',
    'Get-WinCareInterruptedOperation',
    'Get-WinCareInstalledExtension',
    'New-WinCareInstallExtensionPlan',
    'New-WinCareRemoveExtensionPlan',
    'Test-WinCareOperationJournalIntegrity',
    'Request-WinCareOperationCancellation',
    'Start-WinCareLocalBroker',
    'Invoke-WinCareBrokerRequest',
    'Get-WinCareWidgetDefinition',
    'Get-WinCareWidgetSnapshot',
    'New-WinCareWidgetSnapshotExportPlan',
    'Get-WinCareBluetoothDevice',
    'Get-WinCareBluetoothEvent',
    'Get-WinCareMaintenanceWindow',
    'New-WinCareMaintenanceWindowRecord',
    'New-WinCareMaintenanceUpsertPlan',
    'New-WinCareMaintenanceTransitionPlan',
    'Get-WinCareMaintenanceMetrics',
    'New-WinCareMaintenanceMetricsExportPlan',
    'Get-WinCareContextMenuRuleState',
    'New-WinCareContextMenuPlan',
    'Import-WinCareModernContextMenuDefinition',
    'Get-WinCareCustomizationHost',
    'Get-WinCareRainmeterSkinInventory',
    'Get-WinCareWindhawkModInventory',
    'Get-WinCareExplorerPatcherState',
    'Get-WinCarePlaybook',
    'New-WinCarePlaybookPlan',
    'Get-WinCareLocalGroupPolicyState',
    'New-WinCareLocalGroupPolicyImportPlan',
    'Get-WinCareSysmonState',
    'New-WinCareSysmonConfigurationPlan',
    'New-WinCareSysmonUninstallPlan',
    'Get-WinCareMountedWindowsImage',
    'Get-WinCareOfflineImageDriver',
    'Get-WinCareOfflineImagePackage',
    'Get-WinCareOfflineImageFeature',
    'New-WinCareOfflineDriverAddPlan',
    'New-WinCareOfflineDriverRemovePlan',
    'New-WinCareOfflinePackageAddPlan',
    'New-WinCareOfflineFeaturePlan',
    'Get-WinCarePageFileConfiguration',
    'Get-WinCarePageFileRecommendation',
    'New-WinCarePageFilePlan',
    'Get-WinCareSecurityControlState',
    'Get-WinCareSecurityMaintenanceRecord',
    'New-WinCareSecurityMaintenancePlan',
    'New-WinCareSecurityMaintenanceRestorePlan',
    'Get-WinCareTcpGlobalState',
    'Measure-WinCareNetworkEndpoint',
    'Get-WinCareNetworkExperimentHistory',
    'New-WinCareNetworkExperimentPlan',
    'Get-WinCareInjectionSurface',
    'Get-WinCareProcessModuleInventory',
    'Get-WinCareRemoteThreadEvent',
    'Get-WinCareEtwSession',
    'New-WinCareEtwCapturePlan',
    'New-WinCareInjectionSurfaceQuarantinePlan',
    'Get-WinCarePowerSession',
    'New-WinCarePowerSessionPlan',
    'New-WinCarePowerSessionStopPlan',
    'Invoke-WinCarePowerSessionHost',
    'Get-WinCareWindowInventory',
    'Get-WinCareMonitorInventory',
    'Get-WinCareWindowZoneDefinition',
    'New-WinCareWindowZonePlan',
    'New-WinCareWindowTopmostPlan',
    'New-WinCareWindowActivatePlan',
    'New-WinCareEmergencyInputReleasePlan',
    'Get-WinCareScreenColor',
    'ConvertTo-WinCareColorRecord',
    'Get-WinCareColorPalette',
    'New-WinCareColorPaletteAddPlan',
    'New-WinCareColorPaletteRemovePlan',
    'Get-WinCareImageMetadata',
    'Get-WinCareLocalNote',
    'Search-WinCareLocalNote',
    'New-WinCareLocalNotePlan',
    'New-WinCareLocalNoteRemovePlan',
    'Get-WinCareRemoteSupportCatalog',
    'Get-WinCareRemoteSupportSurface',
    'Get-WinCareRemoteSupportConsent',
    'New-WinCareRemoteSupportConsentPlan',
    'New-WinCareRemoteSupportConsentStatePlan',
    'New-WinCareRemoteSupportExpiryReconciliationPlan',
    'New-WinCareRemoteSupportEmergencyPlan',
    'Get-WinCareBrowserWorkspaceSummary',
    'Get-WinCareBrowserExtensionInventory',
    'Get-WinCareExtensionCommand',
    'Get-WinCareDownloadJob',
    'New-WinCareDownloadJobRecord',
    'New-WinCareDownloadJobPlan',
    'New-WinCareDownloadJobRemovePlan',
    'New-WinCareDownloadStartPlan',
    'New-WinCareDownloadStatePlan',
    'New-WinCareDownloadReconcilePlan',
    'New-WinCareDownloadCancelPlan',
    'Get-WinCareTelemetrySnapshot',
    'Get-WinCareTelemetryHistory',
    'New-WinCareTelemetryCapturePlan',
    'New-WinCareTelemetryExportPlan',
    'Get-WinCareLaunchTarget',
    'New-WinCareOpenLaunchTargetPlan',
    'Invoke-WinCareCalculator',
    'Get-WinCareSteamLibraryPath',
    'Get-WinCareSteamGame',
    'Get-WinCareSteamUser',
    'Get-WinCareSteamCloudFile',
    'New-WinCareSteamCloudBackupPlan',
    'New-WinCareSteamCloudRestorePlan',
    'Get-WinCareGameIntegrityFinding',
    'Get-WinCareOfflineProvisionedAppx',
    'Get-WinCareOfflineReductionProfile',
    'Get-WinCareOfflineReductionAssessment',
    'New-WinCareOfflineReductionPlan',
    'Get-WinCareWorkspaceLayout',
    'New-WinCareWorkspaceLayoutRecord',
    'New-WinCareWorkspaceLayoutSavePlan',
    'New-WinCareWorkspaceLayoutRemovePlan',
    'New-WinCareWorkspaceLayoutApplyPlan',
    'Get-WinCareDisplayOverrideState',
    'New-WinCareDisplayOverrideResetPlan',
    'Get-WinCareWlanSurvey',
    'Get-WinCareLogSnapshot',
    'Get-WinCarePeMetadata',
    'Get-WinCareContainerLogMonitorConfiguration',
    'New-WinCareContainerLogMonitorPlan',
    'Get-WinCareTaskBoard',
    'New-WinCareTaskPlan',
    'Get-WinCareLegacyUnsafeProfile',
    'New-WinCareLegacyUnsafeProfilePlan',
    'Get-WinCareHibernateState',
    'Get-WinCareFileWorkspace',
    'New-WinCareFileWorkspacePlan',
    'Get-WinCareWorkspaceStudioProfile',
    'New-WinCareWorkspaceStudioLayoutPlan',
    'Get-WinCareUnifiedSystemSnapshot',
    'New-WinCareMonitoringExportPlan',
    'Get-WinCarePackageArchiveMetadata',
    'Test-WinCareKanataConfiguration',
    'Get-WinCareSyncthingState',
    'New-WinCareWezTermStatusBarPlan',
    'Get-WinCarePlaybookGraph',
    'Get-WinCareBrightnessSchedule',
    'New-WinCareBrightnessSchedulePlan',
    'New-WinCareBrightnessScheduleApplyPlan',
    'Get-WinCareFolderAppearanceState',
    'New-WinCareFolderAppearancePlan',
    'New-WinCareVerifiedPeerToolPlan',
    'New-WinCareAdbInventoryPlan',
    'New-WinCareXboxFullscreenExperiencePlan',
    'Get-WinCareWin32ErrorMessage',
    'Get-WinCareMsiMetadata',
    'Get-WinCareSystemToolkitDiagnostic',
    'Get-WinCareHardeningProfile',
    'Get-WinCareHardeningAssessment',
    'New-WinCareHardeningProfilePlan',
    'Get-WinCareMaintenanceTemplate',
    'New-WinCareMaintenanceTemplatePlan',
    'Get-WinCareSystemShortcutCatalog',
    'New-WinCareSystemShortcutExportPlan',
    'Import-WinCareDownloadBatchDefinition',
    'New-WinCareDownloadBatchPlan',
    'Get-WinCareExperienceStudioRoot',
    'Get-WinCareVisualAssetInfo',
    'Get-WinCareSpriteSheetLayout',
    'New-WinCareVisualAssetManifestPlan',
    'Get-WinCareLocationPrivacyState',
    'New-WinCareLocationPrivacyPlan',
    'Get-WinCareRemoteAccessProfile',
    'Get-WinCareRemoteAccessState',
    'New-WinCareRemoteAccessPlan',
    'Get-WinCarePowerConditionProfile',
    'Get-WinCarePowerConditionAssessment',
    'New-WinCarePowerConditionPlan',
    'Get-WinCareDownloadStrategy',
    'Get-WinCarePrivacyProfile',
    'New-WinCarePrivacyProfilePlan',
    'Get-WinCareExperienceCapabilityCard',
    'Get-WinCareTorrentMetadata',
    'Get-WinCareHardwareInventory',
    'New-WinCareHardwareReportPlan',
    'Get-WinCareMonitorControlState',
    'New-WinCareMonitorControlPlan',
    'Get-WinCareWindowSearch',
    'Get-WinCareExplorerSession',
    'New-WinCareExplorerSessionSavePlan',
    'Get-WinCareExplorerSessionRecord',
    'New-WinCareExplorerSessionRestorePlan',
    'Get-WinCareUiAutomationSnapshot',
    'Get-WinCareAppxRuntimeInventory',
    'Get-WinCareAppxLaunchTarget',
    'New-WinCareAppxLaunchPlan',
    'Get-WinCareArchiveInspection',
    'Get-WinCareServicingMediaInfo',
    'Get-WinCareTerminalEnvironment',
    'New-WinCareTerminalProfileExportPlan',
    'Get-WinCareGuiResourceAudit',
    'Get-WinCareFullscreenShellAssessment',
    'Get-WinCareShellHardwareCapabilityCard',
    'Get-WinCareDiskPressureAssessment',
    'New-WinCareDiskPressureCleanupPlan',
    'New-WinCareDiskPressureAutomationPlan',
    'Import-WinCareWinapp2Catalog',
    'Get-WinCareWinapp2Assessment',
    'New-WinCareWinapp2CleanupPlan',
    'Get-WinCareApplicationDataRelocationProfile',
    'Get-WinCareApplicationDataRelocationAssessment',
    'New-WinCareApplicationDataRelocationPlan',
    'Get-WinCareFilePreviewProfile',
    'Get-WinCareFilePreview',
    'Get-WinCarePreviewHandlerAssessment',
    'New-WinCareFilePreviewExportPlan',
    'Get-WinCareCleanerPreviewCapabilityCard',
    'Start-WinCareGui',
    'Get-WinCareGuiNavigation',
    'Get-WinCareGuiActionCatalog',
    'Get-WinCareFleetNodeInventory',
    'Compare-WinCareFleetPolicyState',
    'Get-WinCareHypervisorIsolationState',
    'New-WinCareVbsHardeningPlan',
    'New-WinCareMicroVmSandboxPlan',
    'Get-WinCareTelemetryLakeRoot',
    'Get-WinCareTelemetryLakeRecord',
    'Get-WinCareTelemetryLakeAggregate',
    'New-WinCareTelemetryLakeIngestPlan',
    'New-WinCareTelemetryLakeRetentionPlan',
    'Test-WinCareTelemetryAnomaly',
    'Get-WinCareBinaryBehaviorProfile',
    'Get-WinCareBinaryIntelligenceCapability',
    'Get-WinCareVbsEnclaveState',
    'New-WinCareVbsEnclaveHardeningPlan',
    'Get-WinCareEbpfSocketRedirectCapability',
    'Get-WinCareEbpfProgramInventory',
    'New-WinCareEbpfSocketProgramAdmission',
    'Get-WinCareForensicTimeline',
    'Get-WinCareMemoryAnomalySummary',
    'New-WinCareWindowsSandboxConfigurationPlan',
    'Get-WinCareDisplayPipelineState',
    'Get-WinCareVirtualDisplayCapability',
    'New-WinCareDisplayCalibrationPlan',
    'Get-WinCareWireGuardTunnelState',
    'Get-WinCareQuicRuntimeCapability',
    'Get-WinCareCapabilityRegistry',
    'Get-WinCareSysmonThreatMap',
    'Audit-WinCareDefenderFirewallRules',
    'Resolve-WinCareDohQuery',
    'Optimize-WinCareCdnRouting',
    'Invoke-WinCareFuzzyDeduplication',
    'Get-WinCareMftDiskReport',
    'Invoke-WinCareOnnxDiagnosticScan',
    'Get-WinCareSmartFailurePrediction',
    'Enable-WinCareEbpfFilter',
    'Set-WinCareMicrosegmentationRule',
    'Audit-WinCareUefiDbxSignatures',
    'Get-WinCareTpmPcrReport',
    'Invoke-WinCarePqcKeyExchange',
    'Protect-WinCarePqcFile',
    'Unprotect-WinCarePqcFile',
    'Synthesize-WinCareCodePatch',
    'Test-WinCarePatchInSandbox',
    'Start-WinCareRaftMeshNode',
    'Stop-WinCareFleetCoordinator',
    'Sync-WinCareFleetPolicies',
    'Predict-WinCareKernelBsodFault',
    'Invoke-WinCarePageTableOptimization',
    'Invoke-WinCareWasiPlugin',
    'Get-WinCareWasiMarketplaceCatalog',
    'Send-WinCareMultiCloudTelemetry',
    'Get-WinCareFleetMeshStatus',
    'Test-WinCareGuiCatalog',
    'Get-WinCareRbacMatrix',
    'Assert-WinCareRolePermission',
    'Test-WinCareGpoEntraDrift',
    'New-WinCareGpoRemediationPlan',
    'Send-WinCareSiemStream',
    'Invoke-WinCareDismServicingCleanup',
    'Get-WinCareStorageHealthTriage',
    'Enable-WinCareGameStateMode',
    'Import-WinCareFancyZonesLayout',
    'Protect-WinCarePqcSignature',
    'Invoke-WinCareMicroVmSandboxTest',
    'Get-WinCareVbsDmaState',
    'Enable-WinCareEbpfSocketGovernance',
    'Start-WinCareWpfDashboardWindow',
    'Invoke-WinCareFleetDeployment',
    'New-WinCareIsolatedStagingDirectory',
    'Remove-WinCareCryptographicFile',
    'Get-WinCareTerminalCellWidth',
    'Get-WinCareEbpfTelemetryStream',
    'Send-WinCareTelemetryEventBusMessage'
)
