namespace WinCare.Application.Commands;

using System.Collections.Generic;

/// <summary>
/// Impact preview generated by an <see cref="ISubsystemCommandExecutor"/> before mutation approval.
/// </summary>
public sealed record CommandPreview(
    string CommandId,
    string Subsystem,
    string Summary,
    IReadOnlyList<string> AffectedTargets,
    long EstimatedImpactBytes = 0,
    bool RequiresElevation = false);
