#!/usr/bin/env python3
"""Command promotion ledger: derived, verifiable progress toward BehaviorVerified.

Production promotion is gated on every catalog command reaching `BehaviorVerified`
(docs/Validation.md), and `tools/finalize_native_release.py` refuses to finalize a
production bundle until that is true. The progress toward that gate lived only in
prose, which is exactly the kind of claim that drifts.

This tool reads the catalog, reports where every command actually stands, and
generates `docs/migration/command-parity-ledger.md` from the data. `--check`
re-derives the document and fails when the checked-in copy disagrees, so the
ledger cannot be edited into a state the catalog does not support.

Promotion is only ever *lowered* by hand in the catalog; nothing here edits it.
"""

from __future__ import annotations

import argparse
import json
import sys
from collections import Counter
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
CATALOG = REPO_ROOT / "src/WinCare.CommandCatalog/Data/commands.json"
LEDGER = REPO_ROOT / "docs/migration/command-parity-ledger.md"

# Promotion ladder, weakest to strongest. A command at stage N has satisfied every
# weaker stage; the ladder is cumulative, matching finalize_native_release.py.
LADDER = ("Cataloged", "ContractVerified", "Implemented", "BehaviorVerified")
FINAL_STAGE = "BehaviorVerified"

# Frozen legacy-parity oracle: IDs that existed before the native catalog. The
# remainder are additional admitted native commands (verified by
# tools/verify_native_foundation.py), which have no legacy counterpart to match.
ORACLE_SIZE = 259


def load_commands(catalog: Path = CATALOG) -> list[dict]:
    """Reads the command catalog and returns its command entries in file order."""
    raw = json.loads(catalog.read_text(encoding="utf-8-sig"))
    commands = raw if isinstance(raw, list) else raw.get("commands", raw.get("Commands", []))
    if not commands:
        raise ValueError(f"no commands found in {catalog}")
    return commands


def reached(stage: str) -> set[str]:
    """Every stage a command at `stage` has satisfied, inclusive."""
    return set(LADDER[: LADDER.index(stage) + 1])


def readiness(commands: list[dict]) -> dict:
    """Computes the promotion posture the release finalizer gates on."""
    statuses = [str(command.get("migrationStatus", "")) for command in commands]
    invalid = sorted(set(statuses) - set(LADDER))
    if invalid:
        raise ValueError(f"unsupported migration status values: {invalid}")
    return {
        "total": len(commands),
        "cataloged": sum(status in reached("Cataloged") for status in statuses),
        "contract_verified": sum(status in reached("ContractVerified") for status in statuses),
        "implemented": sum(status in reached("Implemented") for status in statuses),
        "behavior_verified": sum(status == FINAL_STAGE for status in statuses),
        "production_blockers": sum(status != FINAL_STAGE for status in statuses),
        "production_ready": all(status == FINAL_STAGE for status in statuses),
    }


def by_area(commands: list[dict]) -> list[tuple[str, int, int]]:
    """Per-area (area, total, behavior_verified), busiest area first."""
    counts: Counter[str] = Counter(str(command.get("area", "Unassigned")) for command in commands)
    verified: Counter[str] = Counter(
        str(command.get("area", "Unassigned"))
        for command in commands
        if command.get("migrationStatus") == FINAL_STAGE
    )
    return [(area, total, verified[area]) for area, total in counts.most_common()]


def by_risk(commands: list[dict]) -> list[tuple[str, int, int]]:
    """Per-risk (risk, total, behavior_verified), highest risk first."""
    order = ("Critical", "High", "Moderate", "Low", "ReadOnly")
    counts = Counter(str(command.get("risk", "Unassigned")) for command in commands)
    verified = Counter(
        str(command.get("risk", "Unassigned"))
        for command in commands
        if command.get("migrationStatus") == FINAL_STAGE
    )
    return [(risk, counts[risk], verified[risk]) for risk in order if counts[risk]]


def render(commands: list[dict]) -> str:
    """Renders the ledger document. Deterministic: same catalog, same bytes."""
    state = readiness(commands)
    lines = [
        "# Command parity and promotion ledger",
        "",
        "<!-- Generated by tools/command_promotion.py. Do not edit by hand. -->",
        "",
        "The maintained command contract is the live catalog at "
        "[`../../src/WinCare.CommandCatalog/Data/commands.json`]"
        "(../../src/WinCare.CommandCatalog/Data/commands.json). This file is derived "
        "from it, so it cannot drift from the contract it describes.",
        "",
        "## Why this ledger exists",
        "",
        "`docs/Validation.md` makes production promotion conditional on every command "
        "reaching `BehaviorVerified`, and `tools/finalize_native_release.py` exits "
        "non-zero until that holds. The progress toward that gate was previously "
        "narrated in prose with no artifact behind it. This ledger is that artifact: "
        "regenerate it with `python tools/command_promotion.py --emit` and verify it "
        "in CI with `--check`.",
        "",
        "## Promotion ladder",
        "",
        "Stages are cumulative. A command listed at a stage has satisfied every weaker "
        "stage as well.",
        "",
        "| Stage | Meaning |",
        "|---|---|",
        "| `Cataloged` | The legacy command is cataloged for migration. |",
        "| `ContractVerified` | The command contract has been verified. |",
        "| `Implemented` | The native implementation is available. |",
        "| `BehaviorVerified` | Native behavior has been verified against the legacy command. |",
        "",
        "## Current posture",
        "",
        "| Measure | Value |",
        "|---|---|",
        f"| Commands in catalog | {state['total']} |",
        f"| Frozen legacy-parity oracle | {ORACLE_SIZE} |",
        f"| Additional admitted native commands | {state['total'] - ORACLE_SIZE} |",
        f"| At `ContractVerified` or stronger | {state['contract_verified']} |",
        f"| At `Implemented` or stronger | {state['implemented']} |",
        f"| At `BehaviorVerified` | {state['behavior_verified']} |",
        f"| Production blockers | {state['production_blockers']} |",
        f"| Production ready | {'yes' if state['production_ready'] else 'no'} |",
        "",
        f"Production promotion is currently **{'unblocked' if state['production_ready'] else 'blocked'}**: "
        f"{state['production_blockers']} of {state['total']} commands have not reached "
        "`BehaviorVerified`.",
        "",
        "## Progress by area",
        "",
        "| Area | Commands | Behavior verified |",
        "|---|---:|---:|",
    ]
    for area, total, verified in by_area(commands):
        lines.append(f"| {area} | {total} | {verified} |")

    lines += [
        "",
        "## Progress by risk",
        "",
        "Behavior verification is most valuable on the commands that can do real "
        "damage, so the risk ordering is highest first.",
        "",
        "| Risk | Commands | Behavior verified |",
        "|---|---:|---:|",
    ]
    for risk, total, verified in by_risk(commands):
        lines.append(f"| {risk} | {total} | {verified} |")

    blocking = [c for c in commands if c.get("migrationStatus") != FINAL_STAGE]
    lines += [
        "",
        "## Promoting a command",
        "",
        "1. Execute the command on a supported Windows host and compare its observable "
        "effect against the legacy behavior recorded in `migration/oracle`.",
        "2. Record the result, then set that command's `migrationStatus` to "
        "`BehaviorVerified` in the catalog.",
        "3. Run `python tools/command_promotion.py --emit` to refresh this ledger.",
        "",
        "A command is only promoted on evidence from a real host. A command that is "
        "unreachable, destructive on this machine, or only exercisable with hardware "
        "that is absent stays at its current stage and is called out in review rather "
        "than promoted on the strength of its unit tests.",
    ]
    if blocking:
        lines += [
            "",
            "## Still blocking production promotion",
            "",
            f"{len(blocking)} commands remain below `BehaviorVerified`. Grouped by the "
            "stage they currently occupy:",
            "",
            "| Stage | Commands |",
            "|---|---:|",
        ]
        stages = Counter(str(c.get("migrationStatus", "")) for c in blocking)
        for stage in LADDER[:-1]:
            if stages.get(stage):
                lines.append(f"| `{stage}` | {stages[stage]} |")
    return "\n".join(lines) + "\n"


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--catalog", type=Path, default=CATALOG,
                        help="path to the command catalog (default: the live catalog)")
    parser.add_argument("--emit", action="store_true",
                        help="rewrite the generated ledger from the catalog")
    parser.add_argument("--check", action="store_true",
                        help="fail when the checked-in ledger disagrees with the catalog")
    args = parser.parse_args(argv)

    commands = load_commands(args.catalog)
    state = readiness(commands)

    if args.emit:
        LEDGER.parent.mkdir(parents=True, exist_ok=True)
        LEDGER.write_text(render(commands), encoding="utf-8")
        print(f"wrote {LEDGER.relative_to(REPO_ROOT)}")
    elif args.check:
        if not LEDGER.is_file():
            print(f"missing {LEDGER.relative_to(REPO_ROOT)}", file=sys.stderr)
            return 1
        if LEDGER.read_text(encoding="utf-8") != render(commands):
            print("command parity ledger is stale; run: python tools/command_promotion.py --emit",
                  file=sys.stderr)
            return 1
        print("command parity ledger matches the catalog")
    else:
        print(f"commands:            {state['total']}")
        print(f"behavior verified:    {state['behavior_verified']}")
        print(f"production blockers:  {state['production_blockers']}")
        print(f"production ready:     {'yes' if state['production_ready'] else 'no'}")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
