#!/usr/bin/env python3
"""Append deterministic D110-D129 evidence to cumulative WinCare convergence data."""
from __future__ import annotations
import csv, hashlib, json, os
from collections import Counter
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]; DOCS=ROOT/'docs'/'convergence'
SRC=Path(os.environ.get('WINCARE_WAVE8_DONOR_ROOT','/mnt/data/wincare_wave8_scan/donors'))
SCAN=Path(os.environ.get('WINCARE_WAVE8_ARCHIVE_MANIFEST','/mnt/data/wincare_wave8_scan/wave8-archive-inventory.json'))
LEDGER_COLUMNS=['record_id','parent_record_id','composition_group_id','donor','domain','value_unit','source_granularity','value_form','separability','donor_path','donor_sha256','donor_symbol','transformation','mapping_topology','disposition','decision_rationale','target_capability','target_nodes','invariant','negative_invariant','test_node','operator_surface','migration_impact','license_note','risk_tier','dependency_record_ids','evidence_confidence','validation_status']
SURFACE_COLUMNS=['donor','path','sha256','size_bytes','file_type','language','classification','authority_status','semantic_record_ids','notes']
TEST='tests/Wave8.SystemToolkit.Tests.ps1'
NAMES={
'D110':'WindowsUtils','D111':'Windows Maintenance Tool','D112':'WindowsHardeningScript','D113':'Laravel Scheduled Maintenance','D114':'optimizerDuck','D115':'HardeningKitty','D116':'winpower','D117':'Personalization reference','D118':'duplicacy-utils','D119':'AppWindowUtility','D120':'Windows Super God Mode','D121':'Windows Update Utility','D122':'Drac Maintenance Tool','D123':'winapi-util','D124':'gsudo','D125':'Windows Optimize Debloat','D126':'Windows Context Menu Customizations','D127':'winutil','D128':'AB Download Manager','D129':'torrent-live'}
ROOTS={d:(next((p for p in (SRC/d).iterdir() if p.is_dir()),SRC/d)) for d in NAMES}
ARCH={x['donor_id']:x for x in json.loads(SCAN.read_text())}
SPECS={
'D110':[
('WIN32-ERROR-LOOKUP','Diagnostics','Win32 error-code resolution','src/Commands/Utilities/GetErrorStringCommand.cs','defensive primitive','adapted','Windows diagnostic toolkit','src/WinCare/Providers/105-SystemToolkit.ps1#Get-WinCareWin32ErrorMessage','Numeric error codes resolve without executing donor binaries.','No donor assembly receives authority.','low'),
('MSI-READONLY','Package inspection','Read-only MSI property inspection','src/Commands/Installer/GetMsiPropertiesCommand.cs','inspection mechanism','hardened','MSI metadata inspection','src/WinCare/Providers/105-SystemToolkit.ps1#Get-WinCareMsiMetadata','MSI databases are opened read-only with bounded output.','Inspection cannot install, repair, or transform packages.','medium')],
'D111':[
('DIAGNOSTIC-DASHBOARD','Diagnostics','Maintenance-oriented device and health snapshot','WMT-GUI.ps1','operator workflow','recomposed','Windows diagnostic toolkit','src/WinCare/Providers/105-SystemToolkit.ps1#Get-WinCareSystemToolkitDiagnostic','Diagnostics remain read-only and bounded.','The dashboard cannot mutate state while collecting evidence.','medium'),
('MAINTENANCE-WORKFLOW','Maintenance','Health and cleanup maintenance workflow','WMT-GUI.ps1','workflow','adapted','Maintenance templates','src/WinCare/Providers/105-SystemToolkit.ps1#Get-WinCareMaintenanceTemplate','Maintenance work is represented by revisioned lifecycle records.','A GUI button does not bypass plan authorization.','medium')],
'D112':[('HARDENING-SCRIPT','Security hardening','Registry and audit-policy hardening intent','Harden_PS.ps1','policy mechanism','hardened','Hardening profiles','src/WinCare/Providers/105-SystemToolkit.ps1#New-WinCareHardeningProfilePlan','Each supported hardening value becomes a typed reversible action.','Raw scripts and blanket command execution are not imported.','critical')],
'D113':[('MAINTENANCE-LIFECYCLE','Maintenance','Scheduled maintenance lifecycle and notice semantics','src/ScheduledMaintenance.php','state-machine pattern','recomposed','Maintenance templates','src/WinCare/Providers/105-SystemToolkit.ps1#New-WinCareMaintenanceTemplatePlan','Templates create records in the existing closed WinCare maintenance state machine.','A second maintenance source of truth is not introduced.','medium')],
'D114':[('OPTIMIZER-PRESETS','Optimization','Optimization and restore preset composition','optimizerDuck/Services/Optimization/OptimizationService.cs','product workflow','recomposed','Legacy unsafe profiles','src/WinCare/Providers/106-PeerUtilities.ps1#Get-WinCareLegacyUnsafeProfile','Aggressive presets compose existing typed actions and compensators.','Donor executables and opaque step runners are not imported.','critical')],
'D115':[('HARDENING-CATALOG','Security hardening','Machine-readable hardening finding catalogs','HardeningKitty.psm1','policy catalog','extracted','Hardening profiles','src/WinCare/Providers/105-SystemToolkit.ps1#Get-WinCareHardeningProfile','Selected controls are explicit, versioned, and independently implemented.','Benchmark breadth is not misrepresented as complete implementation.','critical')],
'D116':[('POWER-STATE','Power management','Power and battery status affordances','core.py','operator affordance','superseded','Windows diagnostic toolkit','src/WinCare/Providers/105-SystemToolkit.ps1#Get-WinCareSystemToolkitDiagnostic','Existing WinCare power ownership remains authoritative.','No Python tray runtime is introduced.','low')],
'D117':[
('PERSONALIZATION-POLICIES','Personalization','Dark theme, Spotlight, taskbar, and Settings policy recipes','Personalization(1).txt','configuration reference','adapted','Catalog rules','src/WinCare/Data/Catalog/rules.json#appearance.dark-mode;src/WinCare/Data/Catalog/rules.json#appearance.disable-spotlight','Every adopted registry value is previewed and reversible.','Copy-pasted shell commands are not executed.','high'),
('DEFENDER-UPDATE-REDUCTION','Legacy unsafe','Persistent Defender and Windows Update reduction recipes','Personalization(1).txt','unsafe mutation reference','recomposed','Legacy unsafe profiles','src/WinCare/Providers/106-PeerUtilities.ps1#Get-WinCareLegacyUnsafeProfile','Permanent reductions require exact Critical acknowledgement.','Security reductions cannot run through normal catalog actions.','critical'),
('APPX-RECIPES','App management','Store application remove and restore recipes','Personalization(1).txt','workflow reference','superseded','Existing AppX selection engine','src/WinCare/Providers/108-CleanupMods.ps1#New-WinCareAppxSelectionPlan','Exact installed identities are resolved before mutation.','Unbounded package pipelines are not imported.','critical')],
'D118':[('BACKUP-LIFECYCLE','Backup','Backup, retention, check, and scheduled execution workflow','backup.ps1','operational workflow','adapted','Maintenance templates','src/WinCare/Providers/105-SystemToolkit.ps1#Get-WinCareMaintenanceTemplate','Backup verification is represented as a scheduled maintenance window.','WinCare does not claim to implement Duplicacy itself.','medium')],
'D119':[('WINDOW-BEHAVIOR','Window management','Borderless, topmost, position, and activation behaviors','Runtime/AppWindowUtility.cs','window primitive','superseded','Existing window workspace','src/WinCare/Providers/95-WindowWorkspace.ps1#New-WinCareWindowTopmostPlan','Existing WinCare window plans remain the sole mutation owner.','Unity-specific runtime code is not imported.','medium')],
'D120':[('SYSTEM-SHORTCUT-CATALOG','System navigation','ms-settings, shell, CLSID, and AppX protocol discovery','Super_God_Mode.ps1','catalog workflow','hardened','System shortcut catalog','src/WinCare/Providers/105-SystemToolkit.ps1#Get-WinCareSystemShortcutCatalog','Enumeration is bounded and export remains under WinCare state.','Discovered targets are data, not automatically executed commands.','medium')],
'D121':[('WUA-WORKFLOW','Windows Update','Search, download, and install update workflow','WUU.ps1','workflow','superseded','Existing WUA provider','src/WinCare/Providers/65-WindowsUpdateAgent.ps1#Get-WinCareWuaUpdate','The existing COM-backed typed WUA provider remains authoritative.','A second update installer is not introduced.','high')],
'D122':[('MAINTENANCE-DIAGNOSTICS','Maintenance','Menu-driven maintenance diagnostics','DracUtility79.bat','operator workflow','adapted','Windows diagnostic toolkit','src/WinCare/Providers/105-SystemToolkit.ps1#Get-WinCareSystemToolkitDiagnostic','Useful diagnostics are exposed without shell-string execution.','Batch-menu mutation paths are not imported.','medium')],
'D123':[('WINAPI-ERRORS','Native utilities','Windows API error and console primitives','src/win.rs','native primitive','adapted','Windows diagnostic toolkit','src/WinCare/Providers/105-SystemToolkit.ps1#Get-WinCareWin32ErrorMessage','Only platform-native safe lookup semantics are retained.','A Rust boundary is not added without a target need.','low')],
'D124':[('ELEVATION-BROKER','Elevation','Cached elevation and broker security model','README.md','architecture pattern','superseded','Existing authenticated elevation host','src/WinCare/Core/03-Process.ps1#Invoke-WinCareElevatedAction','WinCare retains HMAC, expiry, contract, policy, and exact-action validation.','gsudo binaries and broad cached elevation are not bundled or invoked.','critical')],
'D125':[('HARDENING-POLICIES','Security hardening','Optimize, debloat, policy, and update reduction presets','sos-optimize-windows.ps1','preset collection','recomposed','Hardening and unsafe profiles','src/WinCare/Providers/105-SystemToolkit.ps1#Get-WinCareHardeningProfile;src/WinCare/Providers/106-PeerUtilities.ps1#Get-WinCareLegacyUnsafeProfile','Selected semantics are decomposed into target-native actions.','Vendored PSWindowsUpdate and raw optimizer scripts are not imported.','critical')],
'D126':[('CONTEXT-MENU-PRESETS','Shell integration','Context-menu customization presets','_ImportMyCustomizations.ps1','preset collection','superseded','Existing context-menu catalog','src/WinCare/Providers/79-Shell.ps1#New-WinCareContextMenuPlan','Existing exact registry-tree snapshots remain authoritative.','Bulk .reg import is not used as an unreviewed execution path.','high')],
'D127':[('HARDENING-PRESETS','System utility','Typed application, tweak, update, and hardening presets','config/tweaks.json','configuration catalog','recomposed','Hardening and unsafe profiles','src/WinCare/Providers/105-SystemToolkit.ps1#Get-WinCareHardeningProfile;src/WinCare/Providers/106-PeerUtilities.ps1#Get-WinCareLegacyUnsafeProfile','Selected presets map to existing target ownership and policy gates.','The donor runspace engine is not embedded.','critical'),('UPDATE-WORKFLOW','Windows Update','Update selection and servicing workflow','functions/public/Invoke-WPFUpdatesdefault.ps1','workflow','superseded','Existing WUA provider','src/WinCare/Providers/65-WindowsUpdateAgent.ps1#Get-WinCareWuaUpdate','Existing update contracts remain authoritative.','No duplicate updater state machine is introduced.','high')],
'D128':[('DOWNLOAD-BATCH','Downloads','Batch download admission and multi-item workflow','desktop/app/src/main/kotlin/com/abdownloadmanager/desktop/pages/batchdownload/DesktopBatchDownloadComponent.kt','product workflow','recomposed','Batch download admission','src/WinCare/Providers/105-SystemToolkit.ps1#Import-WinCareDownloadBatchDefinition','Batches are bounded, schema-checked, and converted to verified BITS job records.','Donor network engines and browser hooks are not imported.','high'),('QUEUE-SCHEDULING','Downloads','Queue, scheduling, mirrors, checksum, and retry semantics','README.md','capability reference','superseded','Existing download queue','src/WinCare/Providers/100-Downloads.ps1#New-WinCareDownloadJobRecord','Existing target queue, hashes, retries, schedules, and BITS reconciliation remain authoritative.','Parallel downloader implementation is not duplicated.','medium')],
'D129':[('TORRENT-METADATA','Package inspection','Local torrent metadata and file inventory','index.js','data parser reference','hardened','Torrent metadata inspection','src/WinCare/Providers/105-SystemToolkit.ps1#Get-WinCareTorrentMetadata','Only bounded local bencode parsing is implemented.','No trackers, peers, DHT, blocklists, or streaming are contacted.','high'),('NETWORK-ENGINE-GUARDRAIL','Network safety','Legacy peer discovery, blocklist, freerider, and streaming engine','lib/peer-discovery.js','negative lesson','rejected-with-reason','n/a','n/a','The stale vendored network runtime is rejected.','WinCare does not execute torrent networking or anti-monitoring behavior.','critical')]
}
LANG={'.ps1':'PowerShell','.psm1':'PowerShell','.psd1':'PowerShell','.cs':'C#','.rs':'Rust','.py':'Python','.php':'PHP','.kt':'Kotlin','.kts':'Kotlin','.js':'JavaScript','.json':'JSON','.csv':'CSV','.reg':'Registry','.bat':'Batch','.cmd':'Batch','.md':'Markdown','.txt':'Text','.xml':'XML','.yml':'YAML','.yaml':'YAML','.png':'Image','.jpg':'Image','.jpeg':'Image','.gif':'Image','.ico':'Image','.svg':'Image','.dll':'Binary','.exe':'Binary'}
def sha(p):
 h=hashlib.sha256()
 with p.open('rb') as f:
  for b in iter(lambda:f.read(1024*1024),b''):h.update(b)
 return h.hexdigest()
def rows(p):
 with p.open(newline='',encoding='utf-8-sig') as f:return list(csv.DictReader(f))
def write(p,cols,data):
 with p.open('w',newline='',encoding='utf-8') as f:w=csv.DictWriter(f,fieldnames=cols,lineterminator='\n');w.writeheader();w.writerows(data)
def classify(rel,p):
 low=rel.lower();ext=p.suffix.lower();name=p.name.lower()
 if '/node_modules/' in '/'+low or low.startswith('node_modules/'):c='vendored'
 elif '/test' in '/'+low or name.endswith(('tests.ps1','test.cs')):c='test'
 elif low.startswith('.github/') or name in {'.gitignore','.gitattributes'}:c='repository-administration'
 elif name.startswith(('license','copying','notice')):c='governance'
 elif name.startswith('readme') or ext in {'.md','.txt'}:c='documentation'
 elif ext in {'.ps1','.psm1','.psd1','.cs','.rs','.py','.php','.kt','.kts','.js','.bat','.cmd'}:c='script' if ext in {'.ps1','.psm1','.py','.bat','.cmd'} else 'implementation'
 elif ext in {'.json','.csv','.reg','.xml','.yml','.yaml','.toml','.ini','.config'}:c='configuration'
 elif ext in {'.png','.jpg','.jpeg','.gif','.ico','.svg'}:c='media'
 elif ext in {'.dll','.exe','.jar'}:c='vendored'
 else:c='repository-administration'
 auth='authoritative' if c in {'implementation','script','configuration'} else ('derived' if c in {'media','vendored'} else 'supporting')
 return ext or '[no-extension]',LANG.get(ext,'Other'),c,auth
def license_note(root):
 licenses=[p for p in root.rglob('*') if p.is_file() and p.name.lower().startswith(('license','copying'))]
 return 'Donor license files were preserved as evidence; no donor source is bundled and behavior is independently implemented.' if licenses else 'No license detected in the supplied surface; only independently implemented concepts, facts, and guardrails are used.'
def main():
 ledger=[r for r in rows(DOCS/'adoption-matrix.csv') if int(r['donor'][1:])<110]
 surfaces=[r for r in rows(DOCS/'surface-accountability.csv') if int(r['donor'][1:])<110]
 inventory=[r for r in json.loads((DOCS/'donor-inventory.json').read_text()) if int(str(r['donor_id'])[1:])<110]
 for d,name in NAMES.items():
  root=ROOTS[d]; files=sorted((p for p in root.rglob('*') if p.is_file() and not p.is_symlink()),key=lambda p:p.relative_to(root).as_posix().casefold())
  parent=f'{d}-SURFACE-ACCOUNTABILITY'; rep='README.md' if (root/'README.md').is_file() else files[0].relative_to(root).as_posix(); links={}
  note=license_note(root)
  ledger.append({'record_id':parent,'parent_record_id':'n/a','composition_group_id':f'CG-W8-{d}-ACCOUNTABILITY','donor':d,'domain':'Donor accountability','value_unit':f'Complete file accountability for {name}','source_granularity':'repository/archive surface','value_form':'accountability evidence','separability':'standalone','donor_path':rep,'donor_sha256':sha(root/rep),'donor_symbol':'n/a','transformation':'evidence inventory and disposition mapping','mapping_topology':'custom:one donor to complete surface accountability','disposition':'reference-only','decision_rationale':'Every supplied regular file was hashed, classified, and linked; material semantics receive narrower child records.','target_capability':'n/a','target_nodes':'n/a','invariant':'No donor surface is silently omitted.','negative_invariant':'File counts are not treated as semantic adoption.','test_node':'n/a','operator_surface':'n/a','migration_impact':'n/a','license_note':note,'risk_tier':'low','dependency_record_ids':'n/a','evidence_confidence':'high','validation_status':'reviewed'})
  for suffix,domain,value,path,form,disp,cap,nodes,inv,neg,risk in SPECS[d]:
   full=root/path
   if not full.is_file(): raise FileNotFoundError(full)
   rid=f'{d}-{suffix}';links.setdefault(path,[]).append(rid)
   ledger.append({'record_id':rid,'parent_record_id':parent,'composition_group_id':f'CG-W8-{suffix}','donor':d,'domain':domain,'value_unit':value,'source_granularity':'mechanism, preset, workflow, data, or negative evidence','value_form':form,'separability':'context-dependent','donor_path':path,'donor_sha256':sha(full),'donor_symbol':'n/a','transformation':'target-native adaptation, hardening, recomposition, supersession, or guardrail derivation','mapping_topology':'many-to-many','disposition':disp,'decision_rationale':f'{value} was compared against WinCare authority, policy, preview, journal, bounded-resource, and recovery models. Donor packaging was not imported.','target_capability':cap,'target_nodes':nodes,'invariant':inv,'negative_invariant':neg,'test_node':TEST if disp!='reference-only' else 'n/a','operator_surface':'System toolkit and Peer Utilities TUI, headless JSON, preview receipts, and transaction journal' if cap!='n/a' else 'n/a','migration_impact':'additive WinCare 4.7 capability; existing authority and persistence owners remain authoritative' if cap!='n/a' else 'n/a','license_note':note,'risk_tier':risk,'dependency_record_ids':'n/a','evidence_confidence':'high','validation_status':'statically-validated' if disp not in {'reference-only'} else 'reviewed'})
  counts=Counter();langs=Counter();total=0
  for f in files:
   rel=f.relative_to(root).as_posix();st=f.stat();total+=st.st_size;ft,lang,cls,auth=classify(rel,f);counts[cls]+=1;langs[lang]+=1
   surfaces.append({'donor':d,'path':rel,'sha256':sha(f),'size_bytes':str(st.st_size),'file_type':ft,'language':lang,'classification':cls,'authority_status':auth,'semantic_record_ids':';'.join([parent]+links.get(rel,[])),'notes':'Classified and linked during cumulative WinCare 4.7 convergence.'})
  a=ARCH[d];inventory.append({'donor_id':d,'name':name,'archive':a['archive'],'archive_sha256':a['sha256'],'duplicate_of':None,'member_count':a['members'],'files':len(files),'regular_files':len(files),'symlinks':[],'expanded_bytes':total,'classifications':dict(sorted(counts.items())),'languages':dict(sorted(langs.items())),'licenses':[f.relative_to(root).as_posix() for f in files if f.name.lower().startswith(('license','copying'))],'manifests':[f.relative_to(root).as_posix() for f in files if f.name.lower() in {'package.json','cargo.toml','composer.json','build.gradle.kts'}],'readmes':[f.relative_to(root).as_posix() for f in files if f.name.lower().startswith('readme')][:100],'issues':[]})
 write(DOCS/'adoption-matrix.csv',LEDGER_COLUMNS,ledger);write(DOCS/'surface-accountability.csv',SURFACE_COLUMNS,surfaces);(DOCS/'donor-inventory.json').write_text(json.dumps(inventory,indent=2,ensure_ascii=False)+'\n')
 print(json.dumps({'donors':len(inventory),'semanticRecords':len(ledger),'surfaces':len(surfaces),'newDonors':20,'newRegularFiles':sum(len([p for p in ROOTS[d].rglob('*') if p.is_file() and not p.is_symlink()]) for d in NAMES)},indent=2))
if __name__=='__main__':main()
